services:
  redis:
    image: redis/redis-stack:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 6379:6379
      - 8001:8001
    restart: unless-stopped
    volumes:
      - redis:/data

  bin:
    build:
      context: .
      dockerfile: bin.Dockerfile
      platforms:
        - linux/amd64
    ports:
      - 9001:9001
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      BASE_RECHECK_TIME: ${BIN_BASE_RECHECK_TIME}
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      MIGRATE: 1
      PARSER_REDIS_QUERY_HOST: redis
      HOSTNAME: 0.0.0.0
      CHROME_EXECUTABLE: /usr/bin/google-chrome
      DATABASE_URL: ${BIN_DATABASE}
    restart: unless-stopped
    volumes:
      - bin-db:/app/apps/bin/db

  telegram-bot:
    build:
      context: .
      dockerfile: telegram-bot.Dockerfile
    environment:
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      MIGRATE: 1
      DATABASE_URL: ${TELEGRAM_DATABASE}
    restart: unless-stopped
    volumes:
      - telegram-bot-db:/app/apps/telegram-bot/db

volumes:
  telegram-bot-db:
  bin-db:
  redis: